package ar.edu.itba.Magic.Backend.Cards;

import java.util.LinkedList;
import java.util.List;

import ar.edu.itba.Magic.Backend.Enums.Attribute;
import ar.edu.itba.Magic.Backend.Enums.CardType;
import ar.edu.itba.Magic.Backend.Mechanics.Mechanics;

/** This card generates a Creature Permanent on casting. */
public class CreatureCard extends Card {
	private Integer attackPoints;
    private Integer defencePoints;
    private List<Attribute> attributes;

    public CreatureCard(CardType cardType, List<Attribute> attributes, Integer attackPoints, Integer defencePoints, Mechanics ability) {
        super(cardType, ability);
        this.attackPoints = attackPoints;
        this.defencePoints = defencePoints;
        this.attributes = attributes;
    }

    public void playCard() {
       this.getAbility().executeOnCasting(this);
    }
    
    /** Gets the attack power of the Creature generated by this card. */
    public Integer getAttackPoints() {
    	return attackPoints;
    }
    
    /** Gets the toughness of the Creature generated by this card. */
    public Integer getDefencePoints() {
    	return defencePoints;
    }
    
    /** Gets a list of Attributes of the creature generated by this card. */
    public List<Attribute> getAttributes() {
    	LinkedList<Attribute> newList = new LinkedList<Attribute>();
    	newList.addAll(attributes);
    	return newList;
    }
}

