package ar.edu.itba.Magic.Backend.Interfaces.Constants;

public enum Event {
	GENERIC_EVENT,
	PERMANENT_ENTERS_PLAY,
	PERMANENT_LEAVES_PLAY,
	UNTAP_STEP,
	UPKEEP_STEP,
	DRAW_CARD_STEP,
	MAIN_PHASE,
	COMBAT_PHASE,
	DECLARE_ATTACKERS_STEP,
	DECLARE_BLOCKERS_STEP,
	COMBAT_DAMAGE_STEP,
	END_OF_COMBAT_PHASE,
	ENDING_PHASE,
	CLEANUP_STEP,
	END_OF_TURN
	
}
