package ar.edu.itba.Magic.Backend.Enums;

/** 
 * This enum represents the state in which the Match's execution is currently halted .
 */
public enum MatchState {
	GAME_OVER,
	AWAITING_CASTING_MANA_PAYMENT,
	AWAITING_ABILITY_MANA_PAYMENT,
	AWAITING_CASTING_TARGET_SELECTION,
	AWAITING_ABILITY_TARGET_SELECTION,
	AWAITING_MAIN_PHASE_ACTIONS,
	AWAITING_STACK_ACTIONS,
	AWAITING_ATTACKER_SELECTION,
	AWAITING_BLOCKER_SELECTION,
	AWAITING_ATTACKER_TO_BLOCK_SELECTION,
	AWAITING_CARD_TO_DISCARD_SELECTION,
	AWAITING_STARTING_PHASE_YES_OR_NO_CONFIRMATION,
	AWAITING_MULLIGAN_CONFIRMATION,
	AWAITING_MANA_BURN_ACKNOWLEDGEMENT,
}
