package ar.edu.itba.Magic.Backend;


/**
 * A LastingEffect is generated by an Ability and affects a target permanent by modifying it in some manner.
 * A LastingEffect must be applied on a target permanent and removed from the target permanent by the Ability
 * that generated it. For a LastingEffect that removes itself, see AutomaticLastingEffect.
 */
public abstract class LastingEffect {

    Permanent target;
    Ability sourceAbility;

    public LastingEffect() {

    }
    
    public void setTarget(Permanent target) {
    	this.target = target;
    }
    
    public Permanent getTarget() {
    	return target;
    }
    
    public Ability getSourceAbility() {
    	return sourceAbility;
    }
    
    public void setSourceAbility(Ability sourceAbility) {
    	this.sourceAbility = sourceAbility;
    }
    
    public abstract void applyEffect();
    
    public abstract void undoEffect();

}
