package ar.edu.itba.Magic.Backend.Effects;

import ar.edu.itba.Magic.Backend.Mechanics.Mechanics;
import ar.edu.itba.Magic.Backend.Permanents.Permanent;

/**
 * A LastingEffect is generated by a Mechanics and affects a target permanent by modifying it in some way.
 * A LastingEffect must be applied on a target permanent and removed from the target permanent by the Mechanics
 * that generated it. For a LastingEffect that removes itself, see AutomaticLastingEffect.
 */
public abstract class LastingEffect {

    Permanent target;
    Mechanics sourceMechanics;

    public LastingEffect(Mechanics sourceMechanics) {
    	this.sourceMechanics = sourceMechanics;
    }
    
    public void setTarget(Permanent target) {
    	this.target = target;
    }
    
    public Permanent getTarget() {
    	return target;
    }
    
    public Mechanics getSourceMechanics() {
    	return sourceMechanics;
    }

    public abstract void applyEffect();
    
    public abstract void undoEffect();

}
